services:
  - type: web
    name: gentax-ai
    env: python
    plan: free

    buildCommand: "./render-build.sh"
    startCommand: "uvicorn GENTAX-AI.gentaxai.main:app --host 0.0.0.0 --port $PORT"

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
